// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDJNJ7ILdFB4wg8C1rTRVwfh_akro9HcI',
    appId: '1:719588327441:web:da4241d96c2d61a691f1b0',
    messagingSenderId: '719588327441',
    projectId: 'felix-cafe',
    authDomain: 'felix-cafe.firebaseapp.com',
    storageBucket: 'felix-cafe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm40hU546H7inlsGtUMQiH-KoI9n-KJqM',
    appId: '1:719588327441:android:bc02f6cac001475891f1b0',
    messagingSenderId: '719588327441',
    projectId: 'felix-cafe',
    storageBucket: 'felix-cafe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDJNJ7ILdFB4wg8C1rTRVwfh_akro9HcI',
    appId: '1:719588327441:web:cbb5e4f2a3810d3591f1b0',
    messagingSenderId: '719588327441',
    projectId: 'felix-cafe',
    authDomain: 'felix-cafe.firebaseapp.com',
    storageBucket: 'felix-cafe.firebasestorage.app',
  );
}
